# Generated by Django 4.0.4 on 2023-02-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planofday',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='planofday',
            old_name='Task',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='planofday',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='planofmonth',
            old_name='Goal',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='planofmonth',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='planofweek',
            old_name='Day',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='planofweek',
            old_name='Task',
            new_name='task',
        ),
    ]
