# Generated by Django 4.0.4 on 2023-02-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_rename_day_planofday_day_rename_task_planofday_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planofweek',
            old_name='day',
            new_name='week_of_year',
        ),
    ]
